.

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,10 +1,22 @@
-echo "🚀 Running pre-commit hook..."
-pnpm lint-staged
+#!/bin/sh
+
+# Run linting and formatting
+npm run lint-staged
 lint_status=$?
 
 if [ $lint_status -ne 0 ]; then
-  echo "❌ Lint-staged failed! Please fix the errors and try committing again."
+  echo "Lint-staged failed! Please fix the errors and try committing again."
   exit $lint_status
 fi
 
-echo "✅ Pre-commit hook completed successfully"
+# Run Typechecking
+npm run type-check
+type_check_status=$?
+
+if [ $type_check_status -ne 0 ]; then
+  echo "Typechecking failed! Please fix the errors and try committing again."
+  exit $type_check_status
+fi
+
+# Ensure the script exits with success if everything passed
+exit 0
